server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /api/ {
    proxy_pass ${BACKEND_SCHEME}://${BACKEND_HOST}${BACKEND_PORT}/api/;
    proxy_ssl_server_name on;
    proxy_ssl_name ${BACKEND_HOST};
    proxy_read_timeout 300s;
    proxy_set_header Host ${BACKEND_HOST};
  }
}
